export const userConstant = {
  GET_USERS_START: "GET_USERS_START",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",
  READ_USER_START: "READ_USER_START",
  READ_USER_SUCCESS: "READ_USER_SUCCESS",
  READ_USER_FAILURE: "READ_USER_FAILURE"
};